### PR TITLE
MNT: remove Python3.5 / add Python3.8 in travis.yml

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- as suggested in #64 remove Python3.5 from build matrix
- also add Python3.8 to build matrix

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ping shoyer Seems to work nicely with Python3.8.

**Comment by shoyer** [comment]
Great, thank you! Would you mind also adding `python_requires` to setup.py as well? That stops people from installing on older versions of Python.

**Comment by kmuehlbauer** [comment]
> Would you mind also adding `python_requires` to setup.py as well?

[x] Done

**Comment by shoyer** [comment]
Thanks!

**Pull request merged**
