### PR TITLE
FIX: only add h5py.Dataset to variables

### LINKED ISSUE #49: Error importing compound type
```
import h5netcdf
import netCDF4
import numpy as np
ncfile = netCDF4.Dataset('test.nc','w',format='NETCDF4')
complex128 = np.dtype([('real',np.float64),('imag',np.float64)])
complex128_t = ncfile.createCompoundType(complex128,'complex128')
ncfile.close()
h5netcdf.File('test.nc', 'r')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.7/site-packages/h5netcdf/core.py", line 683, in __repr__
    return '\n'.join([header] + self._repr_body())
  File "/tmp/venv/lib/python3.7/site-packages/h5netcdf/core.py", line 538, in _repr_body
    ['Attributes:'] +
  File "/tmp/venv/lib/python3.7/site-packages/h5netcdf/core.py", line 537, in <listcomp>
    for k, v in self.variables.items()] +
  File "/tmp/venv/lib/python3.7/site-packages/h5netcdf/core.py", line 112, in dimensions
    self._dimensions = self._lookup_dimensions()
  File "/tmp/venv/lib/python3.7/site-packages/h5netcdf/core.py", line 96, in _lookup_dimensions
    for axis, dim in enumerate(self._h5ds.dims):
AttributeError: 'Datatype' object has no attribute 'dims'
```

```
% h5dump test.nc
HDF5 "test.nc" {
GROUP "/" {
   ATTRIBUTE "_NCProperties" {
      DATATYPE  H5T_STRING {
         STRSIZE 57;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "version=1|netcdflibversion=4.4.1.1|hdf5libversion=1.10.2"
      }
   }
   DATATYPE "complex128" H5T_COMPOUND {
      H5T_IEEE_F64LE "real";
      H5T_IEEE_F64LE "imag";
   }
}
}
```

### LINKED ISSUE #63: AttributeError when opening file with only groups at root level
When I open the this file with no other arguments, h5netcdf raises an AttributeError:

Data available from EUMETSAT: https://www.eumetsat.int/website/home/Satellites/FutureSatellites/MeteosatThirdGeneration/MTGData/MTGUserTestData/index.html  --> ftp://ftp.eumetsat.int/pub/OPS/out/test-data/Test-data-for-External-Users/MTG_FCI_Test-Data/ --> uncompressed

```
import h5netcdf
f = "/path/to/file/W_XX...0067.nc"
ds = h5netcdf.File(f, 'r')
```

results in an `AttributeError` as follows:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5netcdf/core.py", line 719, in __repr__
    return '\n'.join([header] + self._repr_body())
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5netcdf/core.py", line 541, in _repr_body
    ['Attributes:'] +
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5netcdf/core.py", line 540, in <listcomp>
    for k, v in self.variables.items()] +
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5netcdf/core.py", line 114, in dimensions
    self._dimensions = self._lookup_dimensions()
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5netcdf/core.py", line 98, in _lookup_dimensions
    for axis, dim in enumerate(self._h5ds.dims):
AttributeError: 'Datatype' object has no attribute 'dims'
```

Strangely, when run on the commandline I get:

```
Exception ignored in: <function File.close at 0x7f1acf790598>
Traceback (most recent call last):
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5netcdf/core.py", line 701, in close
  File "/media/nas/x21324/miniconda3/envs/py37e/lib/python3.7/site-packages/h5py/_hl/files.py", line 431, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 267, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
```

### PR DESCRIPTION
**Pull request by kmuehlbauer**
As suggested in #49 adds another check to only add h5py.Dataset to variables.

fixes #49
fixes #63

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
This is ready for review, I think.

**Comment by kmuehlbauer** [comment]
rebased onto latest master, @shoyer

**Comment by shoyer** [comment]
Would it be possible to add a unit-test for this? It looks like the issue has the core of what you would need.

**Comment by kmuehlbauer** [comment]
OK, so the test should take the erroring Datatype as input and do not error out. I'll add the test after the weekend, or earlier if I find time.

**Comment by shoyer** [comment]
Yes, that sounds right. Thanks!

**Comment by kmuehlbauer** [comment]
Hope the test is OK.

**Comment by shoyer** [comment]
thanks!

**Pull request merged**
