### PR TITLE
Fix missing attribute exception when writing to groups

### PR DESCRIPTION
**Pull request by bnaul**
See: pydata/xarray#994.

I also made a small change in `core.Group._create_dimension` when checking for unlimited dimensions: presently this throws an exception when `size=0`, which seems incorrect.

### CODE REVIEW

**Comment by shoyer** [comment]
Thanks!

These are simple enough that I'm pretty they are correct, but if there's a straightforward way to write tests that would be even better...

**Comment by bnaul** [comment]
I added a test for a writing a length-0 dimension, but I'm not sure what an appropriate test would be for the `sync/flush` error; the problem was `xarray` was calling that method explicitly and it didn't exist. Maybe there should be a test in `xarray.backends.H5NetCDFStore`?

**Comment by shoyer** [comment]
> Maybe there should be a test for xarray.backends.H5NetCDFStore?

Yeah, that's probably the most straightforward place to check this.

We could also add a sync test in h5netcdf, just to verify that it doesn't error.

**Comment by bnaul** [comment]
Added a `sync` call to the `h5netcdf` tests, hopefully it's good to go now!

**Comment by shoyer** [comment]
Awesome, thanks @bnaul !

I will go ahead an issue an new release shortly

**Comment by shoyer** [comment]
v0.3.1 is on pypi

**Pull request merged**
